name: student_detail
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3

  flutter_lints: ^5.0.0


flutter:

  assets:
    - assets/images/
  uses-material-design: true

